//@ts-nocheck
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Farms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>
      <img src='farmer.png' style={{width: "180px",height: "300px"}}></img>
      <h1>Buy <span>Green</span> to save <span>Green</span></h1>
      </div>
    </div>
  )
}
